# Generated by Django 3.2 on 2022-01-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beat',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='beat',
            name='sku',
        ),
        migrations.AddField(
            model_name='beat',
            name='file',
            field=models.FileField(
                blank=True, null=True, upload_to='media/audio/'),
        ),
    ]
