# Generated by Django 3.2 on 2022-01-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0002_auto_20220125_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
