# Generated by Django 3.2 on 2022-02-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(),
        ),
    ]
