# Generated by Django 3.2 on 2022-02-24 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0005_alter_review_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='date',
        ),
    ]
