# Generated by Django 3.2 on 2022-02-24 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0006_remove_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='beat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beats.beat'),
        ),
    ]
