# Generated by Django 3.2 on 2022-02-03 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0002_auto_20220203_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_email',
            field=models.EmailField(
                blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_full_name',
            field=models.CharField(
                blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL),
        ),
    ]
